[BE] 리뷰 요청
codesquad-member-2020/todo-6 pull request #94
Opened 2020-04-23 11:03 UTC by beemiel

2020-04-25 09:57 UTC, wheejuni requested changes
수고 많으셨습니다! 수정 제안사항 남겨드렸으니 확인해 주시고요,
기초적인 컨벤션 부분은 **각별히** 주의 해주시길 부탁 드릴게요.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/HttpInterceptor.java
> +    private String secretKey = "PizzaIsBest";
`"ChickenIsBest"` 로 리팩토링 부탁드려요.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/HttpInterceptor.java
> +        if(jwtTokenString != null) {
빈 헤더가 왔을 경우에도 대비해서. 
`StringUtils.isEmpty(String str)` 을 사용해 보시는 것도 좋을듯합니다.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/SimpleCorsFilter.java
> +//        response.setHeader("Access-Control-Allow-Origin", "*"); //일케 해줘도 되남
안될 건 없습니다. 범위는 필요에 따라 조정하는 것으로

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/WebConfig.java
> +    HttpInterceptor httpInterceptor() {
Bean의 리턴타입을 선언하실 때는 상위 타입으로 하시는게 좋긴 한데.. 예를 들어 지금 상황 같은 경우엔 `Interceptor` 가 되겠군요. 
예전엔 이게 proxy bean 만드는 과정에서 타입 캐스팅 에러를 발생시키기도 했습니다. 
지금은 문제 안돼서 개발자 취향 문제이긴 합니다. 그냥 주저리주저리 남겨 봅니다.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/controller/ActivityController.java
> +  TodoService todoService;
접근제어자를 빼먹지 맙시다.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/controller/ActivityController.java
> +    return new ResponseEntity<>(new ApiResponse(SuccessMessages.SUCCESS, activities), HttpStatus.OK);
`HttpStatus.OK` 를 주는건 괜찮은데 예를 들어, `activities` 가 빈 리스트인 경우에도 정말 `OK` 인지도 고려되었으며 좋겠습니다.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/controller/CardController.java
> +  TodoService todoService;
접근제어자를 까먹지 맙시다. 
아마 복붙의 흔적인가요? 
복붙도 하지 맙시다.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/controller/TodoController.java
> +  TodoService todoService;
접근제어자를 꼭 붙입시다.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/controller/CardController.java
> +  {
중괄호의 시작은 파라메터 닫는 괄호와 같은 줄에서 해주세요.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/domain/Card.java
> +  @Length(max=500)
등호 앞 뒤로 한칸씩 띄워주세요.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/domain/ProjectRepository.java
> +  @Query("SELECT a.id, a.action, a.source, a.destination, a.created_at, a.card, u.user_id " +
SQL Convention 지켜서 작성해주시니까 보기 예쁘고 좋네요. 대박

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/domain/Section.java
> +    if(position<0) {
부등호 앞뒤로 한칸씩 띄워주시고요.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/domain/Section.java
> +    if(position>=cards.size()) {
여기도 공백 넣어주세요.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/exeption/BaseException.java
> +  public ApiResponse returnErrorMessage() {
요런 응용도 좋네요.

2020-04-25 09:57 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo/exeption/NotFoundData.java
> +public class NotFoundData extends BaseException {
`suffix` 는 `Exception` 으로 맞추시기를 권해드립니다.

2020-05-06 09:17 UTC, honux77 commented on BE/src/main/java/com/codesquad/todo/HttpInterceptor.java
> +    private String secretKey = "PizzaIsBest";
저는 피자가 좋아요.

2020-05-06 09:21 UTC, merged

2020-05-06 09:21 UTC, honux77 commented
수고하셨어요!